language: go
go:
- master
env:
- GOPATH=${GOPATH}:${TRAVIS_BUILD_DIR} TRAVIS=true
script:
- go test -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
- bash <(curl -s https://codecov.io/bash)
