#!/usr/bin/env bash
# 
# Bash completion script for Neon.
# 
# To enable bash completion for neon, copy this file in directory 
# /etc/bash_completion.d/. Next time you open a terminal, neon completion
# should work:
# 
# Completion on targets :
# 
#   $ neon t[TAB]
#   tag test
# 
# Completion on tasks :
# 
#   $ neon -task c[TAB]
#   chdir copy
# 
# Completion on builtins :
# 
#   $ neon -builtin f[TAB]
#   find
# 

_neon()
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    case $prev in
        -task)
            tasks="`neon -tasks`"
            COMPREPLY=( $(compgen -W "${tasks}" -- $cur ) )
            return 0
            ;;
        -builtin)
            builtins="`neon -builtins`"
            COMPREPLY=( $(compgen -W "${builtins}" -- $cur ) )
            return 0
            ;;
    esac

    opts="`neon -targets`"
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return 0
}

complete -F _neon neon
