name:    neon
default: [clean, bin, test, integ]
doc:     'Build file to build neon'
extends:
- ~/.neon/c4s4/build/last/changelog.yml
- ~/.neon/c4s4/build/last/version.yml

properties:
  NAME:         'neon'
  BUILD_DIR:    'build'
  ARC_DIR:      '#{BUILD_DIR}/#{NAME}-#{VERSION}'
  REFERENCE:    'doc/reference.md'
  WIN_SHARE:    '/home/casa/misc/shared'
  DEPENDENCIES:
  - 'gopkg.in/yaml.v2'
  - 'github.com/mattn/anko'
  - 'github.com/mattn/go-zglob'
  - 'github.com/fatih/color'
  - 'github.com/mitchellh/gox'

environment:
  GOPATH: '#{_BASE}'
  PATH:   '#{_BASE}/bin:${PATH}'

targets:

  deps:
    doc: 'Install libraries'
    steps:
    - for: 'dependency'
      in:  'DEPENDENCIES'
      do:
      - print: 'Getting dependecy #{dependency}'
      - 'go get #{dependency}'

  format:
    doc: 'Format Go code'
    steps:
    - 'go fmt #{NAME}'

  test:
    doc: 'Run unit tests'
    steps:
    - 'go test #{NAME}/...'

  integ:
    doc: 'Run an integration test on a build file'
    steps:
    - print: "Running integration test in build file 'test.yml'"
    - 'bin/neon -file test.yml'

  version:
    doc: 'Generate version file'
    steps:
    - print: 'Generating version source file'
    - write: 'src/neon/version.go'
      text:  |
        package main

        var VERSION = "#{VERSION}"

  bin:
    doc: 'Build neon binary'
    depends: version
    steps:
    - print: "Building neon binary in 'bin/neon'"
    - remove: 'bin/neon'
    - 'go install #{NAME}'

  refs:
    doc: 'Generate reference documentation for tasks and builtins'
    depends: bin
    steps:
    - 'bin/neon -refs > #{REFERENCE}'
    # we add and commit reference if modified
    - try:
      - 'git diff --quiet --exit-code #{REFERENCE}'
      catch:
      - 'git add "#{REFERENCE}"'
      - 'git commit -m "Updated reference" "#{REFERENCE}"'

  archive:
    doc: 'Generate distribution archive'
    depends: version
    steps:
    - mkdir: '#{ARC_DIR}/bin/'
    - 'gox -output=#{ARC_DIR}/bin/{{.Dir}}_{{.OS}}_{{.Arch}} #{NAME}'
    - copy: 'LICENSE.txt'
      todir: '#{ARC_DIR}/'
    - 'md2pdf -o #{ARC_DIR}/README.pdf README.md'
    - 'changelog to markdown > #{BUILD_DIR}/CHANGELOG.md'
    - 'md2pdf -o #{ARC_DIR}/CHANGELOG.pdf #{BUILD_DIR}/CHANGELOG.md'
    - remove: '#{BUILD_DIR}/CHANGELOG.md'
    - mkdir: '#{ARC_DIR}/doc'
    - 'md2pdf -o #{ARC_DIR}/doc/quickstart.pdf doc/quickstart.md'
    - 'md2pdf -o #{ARC_DIR}/doc/reference.pdf doc/reference.md'
    - tar:    '#{NAME}-#{VERSION}/**/*'
      dir:    '#{BUILD_DIR}'
      tofile: '#{BUILD_DIR}/#{NAME}-#{VERSION}.tar.gz'

  release:
    depends: [clean, test, refs, archive]
    steps:
    - super:

  clean:
    doc: 'Clean generated files'
    steps:
    - delete: '#{BUILD_DIR}'

  win:
    doc: 'Test integration build file on Windows'
    steps:
    - copy:   'src/neon/test.yml'
      tofile: '/home/casa/misc/shared/build.yml'
    - replace: '/home/casa/misc/shared/build.yml'
      pattern: '../../build'
      with:    'build'
    - 'gox -output=#{WIN_SHARE}/#{NAME} -osarch=windows/386 #{NAME}'
