# Neon Build File (http://github.com/c4s4/neon)

doc:     Build file for NeON
extends: golang
default: [clean, fmt, check, test, bugs]
expose:  [clean, fmt, check, test, bugs, install, release]
configuration: '~/.neon/github.yml'
# GITHUB_TOKEN: 'abcdefghijklmnopqrstuvwxyz0123456789'

properties:
  TEST_OPTS:    ['-cover']
  VERSION_PATH: 'neon/build.NeonVersion'
  REFERENCE:    'doc/reference.md'
  ARC_FILES:
  - files: ['LICENSE.txt', 'README.md', 'bash_completion_neon']
  - {files: 'bin/*', dir: =BUILD_DIR}
  - {files: 'doc/*.pdf', dir: =BUILD_DIR}

targets:

  bugs:
    doc: Run bug build files
    depends: [version-test, build]
    steps:
    - for: file
      in:  'find(joinpath("test", "bugs"), "*.yml")'
      do:
      - 'path = joinpath("test", "bugs", file)'
      - print: "Running build file '={path}'"
      - try:
        - $: ['bin/neon', '-file', =path]

  refs:
    doc: Generate reference documentation
    depends: [version-test, bin]
    steps:
    - print: 'Generating reference documentation'
    - $:  ['={BUILD_DIR}/={NAME}', '-refs']
      1>: ={REFERENCE}
      1x: true
    - try:
      - $: ['git', 'diff', '--quiet', '--exit-code', =REFERENCE]
      - print: 'Reference documentation is up to date'
      catch:
      - print: 'Updating reference documentation'
      - $: ['git', 'add', =REFERENCE]
      - $: ['git', 'commit', '-m', 'Updated reference', =REFERENCE]

  doc:
    doc: Build documentations
    steps:
    - print: 'Generating PDF documentation in ={BUILD_DIR}/doc'
    - mkdir: '={BUILD_DIR}/doc'
    - $: ['md2pdf', '-o', '={BUILD_DIR}/doc/quickstart.pdf', 'doc/quickstart.md']
    - $: ['md2pdf', '-o', '={BUILD_DIR}/doc/usermanual.pdf', 'doc/usermanual.md']
    - $: ['md2pdf', '-o', '={BUILD_DIR}/doc/reference.pdf', 'doc/reference.md']

  archive:
    doc: Generate distribution archive
    depends: [doc, binaries]
    steps:
    - super:

  release:
    doc: Perform release
    depends: [clean, last-tags, version, release-title, check, test, refs, change-list]
    steps:
    - super:
