#!/bin/sh
# 
# Installation script for Unix platforms. To run installation, type :
# 
# $ sh -c "$(curl http://sweetohm.net/dist/neon/install)"
# 
# or (if you don't have curl installed):
# 
# $ sh -c "$(wget -O - http://sweetohm.net/dist/neon/install)"

set -e

# get OS and ARCH and build binary name
os=`uname | tr '[:upper:]' '[:lower:]'`
arch=`uname -m`

if [ "$arch" = "i386" ]; then
    arch="386"
elif [ "$arch" = "x86_64" ]; then
    arch="amd64"
elif [ "$arch" = "arm" ]; then
    arch="arm"
fi

echo "os: ${os}"
echo "arch: ${arch}"

binary="neon-${os}-${arch}"

# set default installation directory
if [ -d "/opt/local/bin" ]
then
    DEFAULT_DIR="/opt/local/bin"
elif [ -d "/opt/bin" ]
then
    DEFAULT_DIR="/opt/bin"
elif [ -d "/usr/local/bin" ]
then
    DEFAULT_DIR="/usr/local/bin"
elif [ -d "/usr/bin" ]
then
    DEFAULT_DIR="/usr/bin"
else
    DEFAULT_DIR="/bin"
fi

# select command to download binary
if hash curl 2>/dev/null
then
    command="curl -o"
elif hash wget 2>/dev/null
then
    command="wget -O"
else
    echo "You must install curl or wget to run this installation script"
    exit 1
fi

# download binary in /tmp/neon and make it executable
${command} /tmp/neon http://sweetohm.net/dist/neon/${binary}
chmod +x /tmp/neon

# prompt for installation directory
read -p "Installation directory [${DEFAULT_DIR}]? " directory
if [ -z "$directory" ]
then
    directory=${DEFAULT_DIR}
fi

# copy binary to installation directory
if [ -w "${directory}" ]
then
    mv /tmp/neon ${directory}
else
    sudo mv /tmp/neon ${directory}
    sudo chown root: ${directory}/neon
fi

echo "neon installed in '${directory}' directory"
